[package]
name = "pong"
version = "0.1.0"
authors = ["Setoh <thomasserre63@gmail.com>"]
edition = "2018"

[dependencies]
engine = { path = "../engine" }

[dependencies.sdl2]
version = "0.34.3"
features = ["mixer", "ttf"]